# See https://fatoni-ach.medium.com/easyly-setup-minio-using-docker-container-b64164e4955e
# This is another example
version: "3"
services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /mnt/data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./data:/mnt/data