# reference https://docs.min.io/docs/minio-docker-quickstart-guide.html
version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    # Specify the restart policy after the container exits to always restart, but do not consider containers that have been stopped
    # when the Docker daemon is started.
    restart: unless-stopped
    # # Data volume mounting path settings, mapping the local directory to the container directory
    volumes:
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment: # set env,Equivalent to -e in the docker run command
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      # login name
      MINIO_ROOT_USER: "root"
      # login password
      MINIO_ROOT_PASSWORD: "password"
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      # file upload&preview port
      - "9000:9000"
      # console access port
      - "9001:9001"